# Generated by Django 4.0.3 on 2022-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='e_mail',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='liurl',
            field=models.CharField(max_length=20, verbose_name='Usuário do LinkedIn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='message',
            field=models.TextField(max_length=512, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Assunto'),
        ),
    ]
