# Generated by Django 4.0.3 on 2022-03-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_alter_person_e_mail_alter_person_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Message',
        ),
    ]
