# Generated by Django 4.0.3 on 2022-03-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefone')),
                ('liurl', models.CharField(max_length=20, verbose_name='Usuário do LinkedIn')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('message', models.TextField(max_length=512, verbose_name='Mensagem')),
            ],
        ),
    ]
